# Generated by Django 5.2.8 on 2026-02-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='statedb',
            name='city',
        ),
    ]
