# Generated by Django 6.0.2 on 2026-02-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_citydb_remove_statedb_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityDb',
        ),
        migrations.DeleteModel(
            name='Listed_properties',
        ),
        migrations.DeleteModel(
            name='Property_type',
        ),
        migrations.DeleteModel(
            name='StateDb',
        ),
    ]
