# Generated by Django 6.0.2 on 2026-02-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0003_delete_citydb_delete_listed_properties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listed_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('property_title', models.CharField(max_length=20, null=True)),
                ('posted_by', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
