# Generated by Django 6.0.2 on 2026-02-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityDb',
        ),
        migrations.DeleteModel(
            name='StateDb',
        ),
    ]
