# Generated by Django 6.0.2 on 2026-02-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
    ]
