# Generated by Django 6.0.2 on 2026-03-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_contactmessage_delete_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_type',
            old_name='property_type',
            new_name='property_types',
        ),
    ]
