# Generated by Django 6.0.2 on 2026-02-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
