# Generated by Django 6.0.2 on 2026-02-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
