# Generated by Django 6.0.2 on 2026-02-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_user_email_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
