# Generated by Django 6.0.2 on 2026-02-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.CharField(max_length=50)),
                ('property_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Sale', 'For Sale'), ('Rent', 'For Rent')], max_length=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('features', models.TextField(blank=True, help_text='List of available features')),
                ('posted_by', models.CharField(max_length=20, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
