# Generated by Django 6.0.2 on 2026-02-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(max_length=50),
        ),
    ]
