# Generated by Django 6.0.2 on 2026-02-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_property_property_type_alter_property_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
