# Generated by Django 6.0.2 on 2026-02-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_alter_property_image1_alter_property_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('For SALE', 'FOR SALE'), ('FOR RENT', 'FOR RENT')], max_length=10, null=True),
        ),
    ]
