# Generated by Django 6.0.2 on 2026-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
