# Generated by Django 6.0.2 on 2026-02-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_lead'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Enquiry',
        ),
    ]
