# Generated by Django 6.0.2 on 2026-02-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_rename_lead_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='property',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='property_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='property_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
