# Generated by Django 6.0.2 on 2026-02-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_remove_enquiry_property_enquiry_property_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
    ]
