# Generated by Django 6.0.2 on 2026-03-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_remove_enquiry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
