# Generated by Django 6.0.2 on 2026-03-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_alter_property_area_alter_property_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
