# Generated by Django 6.0.2 on 2026-03-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_rename_user_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
